Initial commit of fabric version
opencord/p4se pull request #2
Opened 2018-10-19 12:46 UTC by lnobach

- P4 sources
- Wireshark dissectors for cpu headers

2018-10-24 20:50 UTC, ccascone requested changes

2018-10-24 20:50 UTC, ccascone commented on fabric/README.md
> +plane is desgined for the requirements of Deutsche Telekom and includes PPPoE
typo

2018-10-24 20:50 UTC, ccascone commented on README.md
> +The directory `fabric` contains a P4 implementation integrated into a CORD
I believe in the CORD community the wording "CORD leaf switch" is understood as a switch that is part of a leaf-spine network controlled by Trellis. Can this program be controlled by Trellis? Has it been tested in conjunction with other Trellis-controller switches (e.g. spine)? If not I would reword this to something like "integrated into a leaf switch of a CORD-like leaf-spine topology"

2018-10-24 20:50 UTC, ccascone commented on fabric/README.md
> +plane is desgined for the requirements of Deutsche Telekom and includes PPPoE
desgined -> designed

2018-11-02 08:52 UTC, lnobach commented
The issues are fixed now.

2018-11-05 17:03 UTC, merged